[General]
filedialog-path=@Variant(\0\0\0\x11\0\0\0\x37\x66ile:///home/liam/Videos/RoryFirstVideoProjectFile2.mkv)
geometry=@ByteArray(\x1\xd9\xd0\xcb\0\x3\0\0\0\0\0\0\0\0\0\0\0\0\aZ\0\0\x3\xf3\0\0\0\0\0\0\0\0\0\0\aZ\0\0\x3\xf3\0\0\0\0\0\0\0\0\a\x80\0\0\0\0\0\0\0\0\0\0\aZ\0\0\x3\xf3)
store_password=true

[FullScreen]
pos=@Point(0 0)
screen=@Rect(0 0 0 0)
wide=false

[MainWindow]
adv-controls=0
bgSize=@Size(932 938)
pl-dock-status=true
playlist-visible=false
playlistSize=@Size(-1 -1)
status-bar-visible=false

[RecentsMRL]
list=file:///home/liam/Videos/RoryFirstVideoProjectFile2.mkv, file:///home/liam/Desktop/FortniteRAWhandbraked.mov, sftp://10.20.20.2/tank/RoryYouTubeChannelRAW/FirstVideo/Record (online-voice-recorder.com).mp3, file:///run/media/liam/Ventoy/PS4/SHARE/Video%20Clips/Fortnite/Fortnite_20260412202542.mp4
times=74654, 0, 0, 0
