actions = {
  update-props = {
    # Increase the buffer size for Bluetooth specifically
    api.alsa.headroom = 2048
    # Force the node to use a larger chunk size
    node.latency = 1024/48000
  }
}
