CPU_SCALING_GOVERNOR_ON_AC="performance"
CPU_MIN_PERF_ON_AC=0
CPU_MAX_PERF_ON_AC=100
CPU_BOOST_ON_AC=1
CPU_ENERGY_PERF_POLICY_ON_AC="performance"
CPU_SCALING_GOVERNOR_ON_BAT="powersave"
CPU_MIN_PERF_ON_BAT=0
CPU_MAX_PERF_ON_BAT=30
CPU_BOOST_ON_BAT=0
CPU_ENERGY_PERF_POLICY_ON_BAT="power"
INTEL_GPU_MIN_FREQ_ON_AC=300
INTEL_GPU_MAX_FREQ_ON_AC=1300
INTEL_GPU_BOOST_FREQ_ON_AC=1300
INTEL_GPU_MIN_FREQ_ON_BAT=300
INTEL_GPU_MAX_FREQ_ON_BAT=900
INTEL_GPU_BOOST_FREQ_ON_BAT=900
SATA_LINKPWR_ON_AC="medium_power"
SATA_LINKPWR_ON_BAT="min_power"
AHCI_RUNTIME_PM_ON_AC="on"
AHCI_RUNTIME_PM_ON_BAT="auto"
AHCI_RUNTIME_PM_TIMEOUT=15
DISK_IDLE_SECS_ON_AC=0
DISK_IDLE_SECS_ON_BAT=2
PCIE_ASPM_ON_AC="default"
PCIE_ASPM_ON_BAT="powersupersave"
RUNTIME_PM_ON_AC="auto"
RUNTIME_PM_ON_BAT="auto"
USB_AUTOSUSPEND=1
WIFI_PWR_ON_AC="off"
WIFI_PWR_ON_BAT="on"
SOUND_POWER_SAVE_ON_AC=1
SOUND_POWER_SAVE_ON_BAT=1
SOUND_POWER_SAVE_CONTROLLER="Y"
WOL_DISABLE="Y"
NMI_WATCHDOG="0"
PLATFORM_PROFILE_ON_AC="performance"
PLATFORM_PROFILE_ON_BAT="low-power"
